# -*- coding: utf-8 -*-
"""Copy of Mini_Project_05_april_cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WOYI2HUP3RZTWNif8i1bP8XAsYILBNHh
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

CHUNK_SIZE = 40960
DATA_SOURCE_MAPPING = 'chest-xray-pneumonia:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F17810%2F23812%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20240908%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20240908T083256Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D34210873ed334a301eb2f066e8c459ffe44312b784b0108eb7948be7f14d5473e34601d40cd8ea4d534a8c951be586e437d4d4c27a577dbaaa0b98035cfe8a6e4a5dfe75972cd6f3cb170e1b68499520e6abf1e4c9e7c9c9bfd35c7e0b730f3bf8d4df3f46c472d7deddf7b57bf4235b4df82cf8513635c265c27fa43f940042520bedf5e5c58fb83ece1f9cdcc9e5b6f798fdb5cef356803385becd1b936027d88cc8dbf4ac56ea26b7e6a0359f44be297fc276118caee33b71276e5975517d66cb7cee0d3f8b3b3db118b7b31e4a0c3318c4bf738925969937dc2bdeb868a42e6dbd0b66e051915fe91157ac52a3466bf1d6af6023c9f77023da0829d54158'

# Define paths
KAGGLE_INPUT_PATH = '/content/drive/My Drive/kaggle/input'
KAGGLE_WORKING_PATH = '/content/drive/My Drive/kaggle/working'

os.makedirs(KAGGLE_INPUT_PATH, exist_ok=True)
os.makedirs(KAGGLE_WORKING_PATH, exist_ok=True)

for data_source_mapping in DATA_SOURCE_MAPPING.split(','):
    directory, download_url_encoded = data_source_mapping.split(':')
    download_url = unquote(download_url_encoded)
    filename = urlparse(download_url).path
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    zip_file_path = os.path.join(KAGGLE_INPUT_PATH, f'{directory}.zip')

    # Check if the directory already exists
    if not os.path.exists(destination_path):
        os.makedirs(destination_path, exist_ok=True)

        if not os.path.exists(zip_file_path):
            try:
                with urlopen(download_url) as fileres, open(zip_file_path, 'wb') as zfile:
                    total_length = fileres.headers['content-length']
                    print(f'Downloading {directory}, {total_length} bytes compressed')
                    dl = 0
                    data = fileres.read(CHUNK_SIZE)
                    while len(data) > 0:
                        dl += len(data)
                        zfile.write(data)
                        done = int(50 * dl / int(total_length))
                        sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                        sys.stdout.flush()
                        data = fileres.read(CHUNK_SIZE)
                    print(f'\nDownloaded: {directory}')
            except HTTPError as e:
                print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
                continue
            except OSError as e:
                print(f'Failed to load {download_url} to path {destination_path}')
                continue

        # Extract files if they have not been extracted yet
        if not os.listdir(destination_path):
            try:
                with ZipFile(zip_file_path) as zfile:
                    zfile.extractall(destination_path)
                print(f'Uncompressed: {directory}')
            except (zipfile.BadZipFile, tarfile.TarError) as e:
                print(f'Failed to extract {zip_file_path} to {destination_path}')
                continue
    else:
        print(f'Data already exists at {destination_path}')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

import matplotlib.pyplot as plt
import seaborn as sns
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D , MaxPool2D , Flatten , Dropout , BatchNormalization
# from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from keras.callbacks import ReduceLROnPlateau
import cv2
import os

import os

# Check if the directory exists and list its contents
def check_directory_contents(directory):
    if os.path.exists(directory):
        print(f"Contents of {directory}:")
        for root, dirs, files in os.walk(directory):
            for file in files:
                print(os.path.join(root, file))
    else:
        print(f"Directory {directory} does not exist.")

check_directory_contents('/content/drive/My Drive/kaggle/input/chest-xray-pneumonia')

for dirname, _, filenames in os.walk('/kaggle/input'):
    print(dirname)
    for filename in filenames:
        print(os.path.join(dirname, filename))

import os
import cv2
import numpy as np

# Constants
img_size = 150
labels = ['PNEUMONIA', 'NORMAL']

def load_and_preprocess_data(data_dir):
    """
    Loads and preprocesses images from a specified directory.

    Args:
        data_dir (str): Directory path containing subdirectories for each label.

    Returns:
        np.array: Array of preprocessed images.
        np.array: Array of labels corresponding to each image.
    """
    images = []
    labels_list = []

    for label in labels:
        # Construct the path for the current label's directory
        path = os.path.join(data_dir, label)

        # Get the numeric class index for the current label
        class_num = labels.index(label)

        # Check if the directory exists
        if not os.path.exists(path):
            print(f"Directory not found: {path}")
            continue

        # Process each image file in the directory
        for img_file in os.listdir(path):
            img_path = os.path.join(path, img_file)

            try:
                # Read the image as grayscale
                img_arr = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

                if img_arr is None:
                    print(f"Image not loaded correctly: {img_path}")
                    continue

                # Resize the image
                resized_arr = cv2.resize(img_arr, (img_size, img_size))

                # Append the processed image and its label
                images.append(resized_arr)
                labels_list.append(class_num)

            except Exception as e:
                # Print any error that occurs during image processing
                print(f"Error processing image {img_file}: {e}")

    # Convert lists to numpy arrays and return
    return np.array(images), np.array(labels_list)

import pickle
with open('/content/drive/MyDrive/chest_xray_data.pkl', 'rb') as f:
    x_train, y_train, x_test, y_test, x_val, y_val = pickle.load(f)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

y_train

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

"""# Importing the necessary libraries"""

import matplotlib.pyplot as plt
import seaborn as sns
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D , MaxPool2D , Flatten , Dropout , BatchNormalization
# from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from keras.callbacks import ReduceLROnPlateau
import cv2
import os

# Data Visualization & Preprocessing


# Visualization
labels_list = ['Pneumonia' if label == 0 else 'Normal' for label in y_train]

print(len(labels_list))

# Set plot style
plt.figure(figsize=(10, 5))
sns.set_style('darkgrid')
# # Create a count plot to visualize the distribution of the classes in the training set

sns.countplot(x=labels_list)
plt.title('Distribution of Pneumonia and Normal Cases in Training Set')
plt.show()

"""**The data seems imbalanced . To increase the no. of training examples, we will use data augmentation**

**Previewing the images of both the classes**
"""

# Plot the first image in the training set
plt.figure(figsize=(5, 5))
plt.imshow(x_train[0], cmap='gray')
plt.title(labels[y_train[0]])
plt.show()

# Plot the last image in the training set
plt.figure(figsize=(5, 5))
plt.imshow(x_train[-1], cmap='gray')
plt.title(labels[y_train[-1]])
plt.show()

# Normalize the data
x_train = np.array(x_train) / 255
x_val = np.array(x_val) / 255
x_test = np.array(x_test) / 255

# resize data for deep learning
x_train = x_train.reshape(-1, img_size, img_size, 1)
y_train = np.array(y_train)

x_val = x_val.reshape(-1, img_size, img_size, 1)
y_val = np.array(y_val)

x_test = x_test.reshape(-1, img_size, img_size, 1)
y_test = np.array(y_test)

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

# Assuming 'x_train' is your training data (e.g., loaded X-ray images)
# Make sure x_train has shape (num_samples, height, width, channels)

# Create ImageDataGenerator
datagen = ImageDataGenerator(
    featurewise_center=False,  # set input mean to 0 over the dataset
    samplewise_center=False,  # set each sample mean to 0
    featurewise_std_normalization=False,  # divide inputs by std of the dataset
    samplewise_std_normalization=False,  # divide each input by its std
    zca_whitening=False,  # apply ZCA whitening
    rotation_range=30,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    vertical_flip=False

)

# Take a sample image
sample_image = np.expand_dims(x_train[0].copy(), 0)  # Add batch dimension and copy the image

# Generate augmented images
augmented_images = [datagen.flow(sample_image, batch_size=1, seed=i)[0][0] for i in range(9)]

# Display the original and augmented images
plt.figure(figsize=(8, 8))
plt.subplot(3, 3, 1)
plt.imshow(x_train[0], cmap='gray')
plt.title('Original')
plt.axis('off')

for i in range(8):
    plt.subplot(3, 3, i + 2)
    plt.imshow(augmented_images[i], cmap='gray') # Display as is, no uint8 conversion
    plt.title('Augmented')
    plt.axis('off')

plt.show()

datagen.fit(x_train)

import tensorflow as tf
from tensorflow.keras.optimizers import AdamW  # For AdamW
from tensorflow.keras.callbacks import ReduceLROnPlateau, LearningRateScheduler # For Cosine Annealing

import tensorflow as tf
from tensorflow.keras.optimizers import Adam, RMSprop  # Import Adam and RMSprop

def create_model(input_shape, learning_rate, optimizer):
    # ... your model architecture ...
    if optimizer == 'adam':
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer == 'rmsprop':
        optimizer = RMSprop(learning_rate=learning_rate)
    # ... compile the model ...
    return model
def create_model(input_shape=(150, 150, 1), learning_rate=0.001, optimizer_name='adam'): # Changed 'optimizer' to 'optimizer_name'
    model = Sequential()
    model.add(Conv2D(32, (5, 5), strides=1, padding='same', activation='relu', input_shape=input_shape))
    model.add(BatchNormalization())
    model.add(MaxPool2D((2, 2), strides=2, padding='same'))
    model.add(Conv2D(64, (3, 3), strides=1, padding='same', activation='relu'))
    model.add(Dropout(0.1))
    model.add(BatchNormalization())
    model.add(MaxPool2D((2, 2), strides=2, padding='same'))
    model.add(Conv2D(64, (3, 3), strides=1, padding='same', activation='relu'))
    model.add(BatchNormalization())
    model.add(MaxPool2D((2, 2), strides=2, padding='same'))
    # ADDED Conv2D Block 3 (New Block!)
    model.add(Conv2D(128, (3, 3), strides=1, padding='same', activation='relu'))
    model.add(BatchNormalization())
    model.add(MaxPool2D((2, 2), strides=2, padding='same'))
    model.add(Dropout(0.2))
    model.add(Conv2D(128, (3, 3), strides=1, padding='same', activation='relu'))
    model.add(Dropout(0.2))
    model.add(BatchNormalization())
    model.add(MaxPool2D((2, 2), strides=2, padding='same'))
    model.add(Conv2D(256, (3, 3), strides=1, padding='same', activation='relu'))
    model.add(Dropout(0.2))
    model.add(BatchNormalization())
    model.add(MaxPool2D((2, 2), strides=2, padding='same'))
    model.add(Flatten())
    model.add(Dense(units=128, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(units=1, activation='sigmoid'))

    if optimizer_name == 'adam': # Changed 'optimizer' to 'optimizer_name'
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer_name == 'rmsprop': # Changed 'optimizer' to 'optimizer_name'
        optimizer = RMSprop(learning_rate=learning_rate)
    elif optimizer_name == 'adamw':
        optimizer = AdamW(learning_rate=learning_rate, weight_decay=0.001) # You can tune weight_decay

    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
    return model

def tune_hyperparameters(x_train, y_train, x_val, y_val, param_grid, epochs=10):
    best_accuracy = 0
    best_params = None

    for lr in param_grid['learning_rate']:
        for opt in param_grid['optimizer']:
            print(f"Trying lr={lr}, opt={opt}")
            model = create_model(learning_rate=lr, optimizer_name=opt)  # Changed 'optimizer'
            history = model.fit(datagen.flow(x_train, y_train, batch_size=32), epochs=epochs, validation_data=datagen.flow(x_val, y_val), verbose=0)

            val_accuracy = np.max(history.history['val_accuracy'])
            if val_accuracy > best_accuracy:
                best_accuracy = val_accuracy
                best_params = {'learning_rate': lr, 'optimizer': opt}

    print(f"Best Validation Accuracy: {best_accuracy}")
    print(f"Best Hyperparameters: {best_params}")
    return best_params

# Cosine Annealing Learning Rate Scheduler
def cosine_annealing(epoch, initial_learning_rate=0.001, T_max=10): # You can tune initial_learning_rate and T_max
    return initial_learning_rate * (1 + np.cos(np.pi * epoch / T_max)) / 2

# Define parameter grid
param_grid = {
    'learning_rate': [0.001, 0.0001, 0.00001],
    'optimizer': ['adam', 'rmsprop', 'adamw']  # Added 'adamw'
}

# Split training data for tuning
x_train_tune, x_val_tune, y_train_tune, y_val_tune = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

# Tune hyperparameters
best_params = tune_hyperparameters(x_train_tune, y_train_tune, x_val_tune, y_val_tune, param_grid, epochs=10)

# ReduceLROnPlateau callback
learning_rate_reduction = ReduceLROnPlateau(
    monitor='val_accuracy',
    patience=3,  # Increased patience
    verbose=1,
    factor=0.2,  # Reduced factor
    min_lr=0.000001
)

# Cosine Annealing callback
cosine_annealing_lr = LearningRateScheduler(cosine_annealing)

# Train the final model with the best parameters
model = create_model(learning_rate=best_params['learning_rate'], optimizer_name=best_params['optimizer']) # Changed 'optimizer'
history = model.fit(
    datagen.flow(x_train, y_train, batch_size=32),
    epochs=30,
    validation_data=datagen.flow(x_val, y_val),
    callbacks=[learning_rate_reduction]  # Or use cosine_annealing_lr
)

print("Loss of the model is - " , model.evaluate(x_test,y_test)[0])
print("Accuracy of the model is - " , model.evaluate(x_test,y_test)[1]*100 , "%")

# Save the entire model to a file
model.save('cnn_90.h5')

# Save only the weights
model.save_weights('model.weights.h5')

# Save the entire model in Keras format
model.save('CNN_inKeras.keras')

